### PR TITLE
Caching Poseidon

### PR DESCRIPTION
**Pull request by filiplazovic**
WIP

`lazy_static` compiles 💯 

Spec for this: https://www.notion.so/hicommonwealth/Pallet-Optimization-7c6d597ef1a34d829f305b56dc4ae695

### CODE REVIEW

**Comment by drewstone** [comment]
Do you think we should add this as a trait parameter?

**Comment by filiplazovic** [comment]
The way I understood is:
Since Config is a trait that defines types, we can add values to it.

If we wanted to define it `parameter_types`, like so:
```rust
parameter_types! {
    pub PoseidonHasher: Poseidon = PoseidonBuilder::new(6).sbox(PoseidonSbox::Exponentiation3).build();
}
```
It would result to:
```rust
struct PoseidonHasher;

impl<I: From<Poseidon>> Get<I> for PoseidonHasher {
	fn get() -> I {
		I::from(PoseidonBuilder::new(6).sbox(PoseidonSbox::Exponentiation3).build())
	}
}
```

Which would build a new Poseidon instance every time we call `get`. Looking from the source code https://substrate.dev/rustdocs/v3.0.0/src/frame_support/lib.rs.html#204-216

Can you confirm that this is correct?

**Comment by drewstone** [comment]
Yea I support adding it to the config, and its important that its built before inclusion into the runtime. This way the instance always exists in WASM and doesn't need reloading. We should allow for sufficient generators so that its useful for other tree sizes.

Let me know what you think. Would be good to see benchmarks for this as well.

**Comment by drewstone** [comment]
Also if you could remove the CI if we have opted for github actions please do so.

**Comment by filiplazovic** [comment]
But the Config doesn't allow that. Config will cache values that are constants, but Poseidon is not a constant

**Pull request merged**
