### PR TITLE
Cleanup unused files

### PR DESCRIPTION
**Pull request by drewstone**

### CODE REVIEW

**Comment by filiplazovic** [comment]
CI needs to be set up, and also `merkle/benches` is obsolete

**Comment by drewstone** [comment]
All set afaik @filiplazovic

**Comment by filiplazovic** [comment]
What about the `web` folder, it was used for testing `wasm-utils`, but now we have more tests, not sure if it's needed, haven't used it in a while

**Comment by filiplazovic** [comment]
LGTM, can be merged when CI passes

**Pull request merged**
